// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-lWzrWhsaMJztijpF0FscqV4bQUHKfkc',
    appId: '1:278657586860:web:8ec2ffac9a1f3ce6b9b109',
    messagingSenderId: '278657586860',
    projectId: 'fooddeliveryapp-1ca5c',
    authDomain: 'fooddeliveryapp-1ca5c.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-1ca5c.appspot.com',
    measurementId: 'G-ZVTS765X6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0maMEpRafqU1S2snjpDZoOBpC2q_hx3A',
    appId: '1:278657586860:android:94f062d1bab80110b9b109',
    messagingSenderId: '278657586860',
    projectId: 'fooddeliveryapp-1ca5c',
    storageBucket: 'fooddeliveryapp-1ca5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPWjU3J_S0ZeskoqKzhESLz6gbqbFvD6Q',
    appId: '1:278657586860:ios:4d104051de63ee6bb9b109',
    messagingSenderId: '278657586860',
    projectId: 'fooddeliveryapp-1ca5c',
    storageBucket: 'fooddeliveryapp-1ca5c.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPWjU3J_S0ZeskoqKzhESLz6gbqbFvD6Q',
    appId: '1:278657586860:ios:4d104051de63ee6bb9b109',
    messagingSenderId: '278657586860',
    projectId: 'fooddeliveryapp-1ca5c',
    storageBucket: 'fooddeliveryapp-1ca5c.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-lWzrWhsaMJztijpF0FscqV4bQUHKfkc',
    appId: '1:278657586860:web:9d4e4d63558548b3b9b109',
    messagingSenderId: '278657586860',
    projectId: 'fooddeliveryapp-1ca5c',
    authDomain: 'fooddeliveryapp-1ca5c.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-1ca5c.appspot.com',
    measurementId: 'G-GZ639D7W9B',
  );
}
